name: Run test
on: [workflow_dispatch]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: v20.8.0
      - run: echo "Current branch is ${{ github.ref }}"
      - run: npm install --legacy-peer-deps
      - run: npx playwright test test/Local_login.spec.js
      - run: echo "Test scripte should be launched here."
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     # This step checks out a copy of your repository.
  #     - uses: actions/checkout@v2
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl version
  #     - run: flyctl auth whoami -t ${{ secrets.FLY_API_TOKEN }}
  #     - run: flyctl deploy --remote-only -t ${{ secrets.FLY_API_TOKEN }}
